### ISSUE TITLE
add topics in About section

### ISSUE THREAD

**Issue by Beliavsky** [nbren12/call_py_fort#18]
I suggest adding the topics `interoperability`, `python`, `fortran` in the About section at https://github.com/nbren12/call_py_fort .

I made this suggestion before but would like to clarify that I am talking about adding tags in the About section, as described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by nbren12** [comment]
Thanks for clarifying your suggestion. I added these topics.
